In [2]:
import numpy as np

In [3]:
import pandas as pd

In [9]:
#1.	Create a Pandas Series from the list [10, 20, 30, 40]. 
list = [10,20,30,40]
print("This is List:", list)
a = pd.Series(list)
print("This is Series:", a)

This is List: [10, 20, 30, 40]
This is Series: 0    10
1    20
2    30
3    40
dtype: int64

In [12]:
#2.	Create a Series from the list [100, 200, 300] using the index labels ['a', 'b', 'c']. 
list1 = [100,200,300]
print(list1)
labels = ["a","b","c"]
a = pd.Series(list1,index=labels)
a

[100, 200, 300]

a    100
b    200
c    300
dtype: int64

In [15]:
#3.	Create a Series from the dictionary {'x': 5, 'y': 10, 'z': 15}. 
dict = {"X":5, "y":10,"z":15}
b = pd.Series(dict)
b

X     5
y    10
z    15
dtype: int64

In [19]:
#4.	Display the value corresponding to index 'y' from the above Series. 
b[["y"]]

y    10
dtype: int64

In [20]:
#5.	Create a DataFrame using: 
data = {
    "Name" : ["Rahul", "Priya", "Amit", "Neha"], 
    "Age" : [22, 21, 23, 22] ,
    "City" : ["Pune", "Mumbai", "Nashik", "Delhi"]
}
data

{'Name': ['Rahul', 'Priya', 'Amit', 'Neha'],
 'Age': [22, 21, 23, 22],
 'City': ['Pune', 'Mumbai', 'Nashik', 'Delhi']}

In [5]:
#6.	Create the same DataFrame using a list of lists. 
data = [
    ["Rahul", 22, "Pune"],
    ["Priya", 21, "Mumbai"],
    ["Amit", 23, "Nashik"],
    ["Neha", 22, "Delhi"]
]

df = pd.DataFrame(data, columns=["Name", "Age", "City"])
df

    Name  Age    City
0  Rahul   22    Pune
1  Priya   21  Mumbai
2   Amit   23  Nashik
3   Neha   22   Delhi

In [6]:
#7.	Display only the Name column. 
print(df["Name"])

0    Rahul
1    Priya
2     Amit
3     Neha
Name: Name, dtype: object

In [7]:
#8.	Display only the Name and City columns. 
print(df[["Name", "City"]])

    Name    City
0  Rahul    Pune
1  Priya  Mumbai
2   Amit  Nashik
3   Neha   Delhi

In [8]:
#9.	Display the first two rows using .loc. 
print(df.loc[0:1])

    Name  Age    City
0  Rahul   22    Pune
1  Priya   21  Mumbai

In [9]:
#10.	Display the third row using .iloc. 
print(df.iloc[2])

Name      Amit
Age         23
City    Nashik
Name: 2, dtype: object

In [10]:
#11.	Add a new column called Marks with values [78, 85, 90, 67]. 
df["Marks"] = [78, 85, 90, 67]
df

    Name  Age    City  Marks
0  Rahul   22    Pune     78
1  Priya   21  Mumbai     85
2   Amit   23  Nashik     90
3   Neha   22   Delhi     67

In [11]:
#12.Add a new column called Course with values ['Python', 'Java', 'Python', 'Data Science']. 
df["Course"] = ["Python", "Java", "Python", "Data Science"]

print(df)

    Name  Age    City  Marks        Course
0  Rahul   22    Pune     78        Python
1  Priya   21  Mumbai     85          Java
2   Amit   23  Nashik     90        Python
3   Neha   22   Delhi     67  Data Science

In [12]:
#13.Remove the City column from the DataFrame. 
df = df.drop("City", axis=1)

print(df)

    Name  Age  Marks        Course
0  Rahul   22     78        Python
1  Priya   21     85          Java
2   Amit   23     90        Python
3   Neha   22     67  Data Science

In [13]:
#14.	Remove the row with index 1. 
df = df.drop(1)

print(df)

    Name  Age  Marks        Course
0  Rahul   22     78        Python
2   Amit   23     90        Python
3   Neha   22     67  Data Science

In [14]:
#15.	Display all students whose age is greater than 22. 
print(df[df["Age"] > 22])

   Name  Age  Marks  Course
2  Amit   23     90  Python

In [17]:
#16.	Display all students whose city is 'Pune'. 
data = {
    "Name": ["Rahul", "Priya", "Amit", "Neha"],
    "Age": [22, 21, 23, 22],
    "City": ["Pune", "Mumbai", "Nashik", "Delhi"]
}

df = pd.DataFrame(data)
df[df["City"] == "Pune"]

    Name  Age  City
0  Rahul   22  Pune

In [18]:
#17
df[(df["Age"] > 21) & (df["City"] == "Delhi")]

   Name  Age   City
3  Neha   22  Delhi

In [21]:
#18
df = pd.read_csv("student.csv")

print(df.head(3))

    Name  Age    City  Marks  Course
0  Rahul   22    Pune     78  Python
1  Priya   21  Mumbai     85    Java
2   Amit   23  Nashik     90  Python

In [23]:
#19
df = pd.read_csv("student.csv")

print(df[["Name", "Marks"]])

    Name  Marks
0  Rahul     78
1  Priya     85
2   Amit     90
3   Neha     67
4  Rohan     88
5  Sneha     92
6  Karan     75
7  Pooja     81

In [33]:
#20
df = pd.read_execl("students.xlsx")

print(df.head())

AttributeError: module 'pandas' has no attribute 'read_excl'

In [35]:
#21
df = pd.read_csv("student.csv")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 8
Columns: 5

In [36]:
#22
print("Maximum Marks:", df["Marks"].max())
print("Minimum Marks:", df["Marks"].min())

Maximum Marks: 92
Minimum Marks: 67

In [37]:
#23
print(df["Marks"].mean())

82.0

In [38]:
#24
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      object
 1   Age     8 non-null      int64
 2   City    8 non-null      object
 3   Marks   8 non-null      int64
 4   Course  8 non-null      object
dtypes: int64(2), object(3)
memory usage: 452.0+ bytes

In [39]:
#25
import pandas as pd
import numpy as np

data = {
    "Name": ["Rahul", "Priya", None],
    "Age": [22, np.nan, 23],
    "Marks": [78, 85, np.nan]
}

df = pd.DataFrame(data)

print(df.isnull())

    Name    Age  Marks
0  False  False  False
1  False   True  False
2   True  False   True

In [40]:
#26
df.isnull().sum()

Name     1
Age      1
Marks    1
dtype: int64

In [41]:
#27
df.isnull().any()

Name     True
Age      True
Marks    True
dtype: bool

In [44]:
#28
df["Age"] = df["Age"].fillna(df["Age"].mean())
df

    Name   Age  Marks
0  Rahul  22.0   78.0
1  Priya  22.5   85.0
2   None  23.0    NaN

In [46]:
#29
df["Marks"] = df["Marks"].fillna(0)
df

    Name   Age  Marks
0  Rahul  22.0   78.0
1  Priya  22.5   85.0
2   None  23.0    0.0

In [47]:
#30
df.dropna()

    Name   Age  Marks
0  Rahul  22.0   78.0
1  Priya  22.5   85.0

In [48]:
#31
data = {
    "Product": ["Laptop", "Phone", "Headphones", "Mouse", "Keyboard"],
    "Category": ["Electronics", "Electronics", "Electronics", "Accessories", "Accessories"],
    "Price": [50000, 25000, 2000, 800, 1500],
    "Quantity": [5, 10, 15, 20, 8]
}

df = pd.DataFrame(data)

print(df)

      Product     Category  Price  Quantity
0      Laptop  Electronics  50000         5
1       Phone  Electronics  25000        10
2  Headphones  Electronics   2000        15
3       Mouse  Accessories    800        20
4    Keyboard  Accessories   1500         8

In [50]:
#32
df[df["Category"] == "Electronics"]

      Product     Category  Price  Quantity
0      Laptop  Electronics  50000         5
1       Phone  Electronics  25000        10
2  Headphones  Electronics   2000        15

In [52]:
#33
df[df["Price"] > 10000]

  Product     Category  Price  Quantity
0  Laptop  Electronics  50000         5
1   Phone  Electronics  25000        10

In [53]:
#34
df["Price"].mean()

np.float64(15860.0)

In [54]:
#35
df.loc[df["Price"].idxmax()]

Product          Laptop
Category    Electronics
Price             50000
Quantity              5
Name: 0, dtype: object

In [55]:
#36
df.loc[df["Price"].idxmin()]

Product           Mouse
Category    Accessories
Price               800
Quantity             20
Name: 3, dtype: object

In [56]:
#37
df[df["Quantity"] > 7]

      Product     Category  Price  Quantity
1       Phone  Electronics  25000        10
2  Headphones  Electronics   2000        15
3       Mouse  Accessories    800        20
4    Keyboard  Accessories   1500         8

In [57]:
#38
df["Total_Price"] = df["Price"] * df["Quantity"]

print(df)

      Product     Category  Price  Quantity  Total_Price
0      Laptop  Electronics  50000         5       250000
1       Phone  Electronics  25000        10       250000
2  Headphones  Electronics   2000        15        30000
3       Mouse  Accessories    800        20        16000
4    Keyboard  Accessories   1500         8        12000

In [58]:
#39
print(df[["Product", "Total_Price"]])

      Product  Total_Price
0      Laptop       250000
1       Phone       250000
2  Headphones        30000
3       Mouse        16000
4    Keyboard        12000

In [59]:
#40
print(df["Quantity"].sum())

58